executor: "KubernetesExecutor"

images:
  airflow:
    repository: "apache/airflow"
    tag: "2.9.2"

serviceAccount:
  create: true
  name: "airflow"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::897722700244:role/platform-org-dev-airflow-role"

webserver:
  replicas: 2
  service:
    type: LoadBalancer
    port: 8080

scheduler:
  replicas: 2

#  Disable bundled Postgres (we use RDS instead)
postgresql:
  enabled: false

extraEnvFrom:
  - secretRef:
      name: airflow-db-secret

#  PVCs for logs/DAGs
logs:
  remoteLogging: true
  remoteLogConnId: "S3_LOGS"
  remoteBaseLogFolder: "s3://yourorg-data-dev-airflow-logs/airflow-logs"

dags:
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: gp2
  gitSync:
    enabled: true
    repo: "https://github.com/KarthikKunchala23/data-platform-dags.git"
    branch: main
    subPath: "dags"
    depth: 1
    syncWait: 60

rbac:
  create: true

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - airflow
        topologyKey: "kubernetes.io/hostname"

metrics:
  enabled: true
