apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: airflow
  source:
    repoURL: https://github.com/KarthikKunchala23/airflow-helm.git
    targetRevision: main
    path: charts/airflow
    helm:
      releaseName: airflow
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
