name: Deploy Airflow Chart (trigger ArgoCD sync)

on:
  push:
    branches:
      - main
    paths:
      - 'charts/airflow/**'
      - 'apps/argocd/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install argocd CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Trigger Argo CD sync (via token)
        if: ${{ secrets.ARGOCD_SERVER != '' && secrets.ARGOCD_TOKEN != '' }}
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
        run: |
          argocd login $ARGOCD_SERVER --auth-token $ARGOCD_TOKEN --insecure
          argocd app sync airflow --server $ARGOCD_SERVER || true
          argocd app wait airflow --server $ARGOCD_SERVER --health --timeout 300 || true

      - name: Done
        run: echo "ArgoCD sync requested for Airflow app"
